description: Creates and uploads a new configuration version, and triggers a run on Terraform Cloud

docker:
  - image: cimg/base:2021.05

parameters:
  organization:
    type: string
    description: Terraform Cloud organization name
  workspace:
    type: string
    description: Terraform Cloud workspace name
  path:
    type: string
    description: Path to the Terraform configuration files
    default: .
  plan-only:
    type: boolean
    description: If the configuration should be speculative
    default: false

steps:
  - checkout
  - lookup-workspace:
      organization: << parameters.organization >>
      workspace: << parameters.workspace >>
  - create-config-version:
      path: << parameters.path >>
  - trigger-run:
      organization: << parameters.organization >>
      workspace: << parameters.workspace >>
